# Generated by Django 4.2.7 on 2024-03-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0014_remove_sip_current_value'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='sip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sip_transactions', to='mutual_sip.sip'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
