# Generated by Django 4.2.7 on 2024-03-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_annual_return_rate', models.FloatField(blank=True, default=0.0)),
                ('annual_return_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sip_status', models.CharField(default='active', max_length=100)),
                ('sip_photo', models.ImageField(max_length=300, null=True, upload_to='user_image')),
                ('users', models.ManyToManyField(blank=True, related_name='sips_taken', to='account.userpurchaseorderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SIP_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_investors', models.IntegerField(blank=True, default=0, null=True)),
                ('total_investment', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_amount', models.FloatField(default=0.0)),
                ('time_period', models.IntegerField()),
                ('current_value', models.FloatField(blank=True, default=0.0)),
                ('sip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sipdetails', to='mutual_sip.sip')),
            ],
        ),
    ]
