# Generated by Django 4.2.7 on 2023-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_usersipdetails_alter_user_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_annual_return_rate', models.FloatField(default=0.0)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.FloatField(default=0.0)),
                ('time_period', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_of_investers', models.IntegerField()),
                ('total_investment', models.FloatField(default=0.0)),
                ('investment_type', models.CharField(max_length=100)),
                ('sip_status', models.CharField(default='active', max_length=100)),
                ('gain_value', models.FloatField(default=0.0)),
                ('user', models.ManyToManyField(to='account.usersipdetails')),
            ],
        ),
    ]
