# Generated by Django 4.2.7 on 2024-03-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip_details',
            name='gain_value',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sip_details',
            name='sip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip', to='mutual_sip.sip'),
        ),
    ]
