# Generated by Django 4.2.7 on 2023-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='min_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
