# Generated by Django 4.2.7 on 2024-03-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0002_sip_details_gain_value_alter_sip_details_sip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='sip',
            name='min_amount',
            field=models.IntegerField(blank=True, default=0.0),
        ),
    ]
