# Generated by Django 4.2.7 on 2024-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0003_sip_description_sip_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='description',
            field=models.TextField(blank=True, default='sip details'),
        ),
    ]
