# Generated by Django 4.2.7 on 2024-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0004_alter_sip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='min_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
