# Generated by Django 4.2.7 on 2023-12-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_usersipdetails_sips_usersipdetails_sips'),
        ('mutual_sip', '0005_remove_sip_users_sip_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='users',
            field=models.ManyToManyField(null=True, related_name='sips_taken', to='account.usersipdetails'),
        ),
    ]
