# Generated by Django 4.2.7 on 2024-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0006_alter_sip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
