# Generated by Django 4.2.7 on 2023-12-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0007_alter_sip_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='no_of_investors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sip',
            name='total_investment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
