# Generated by Django 4.2.7 on 2024-03-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0007_alter_sip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sip',
            name='min_amount',
        ),
    ]
