# Generated by Django 4.2.7 on 2023-12-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_referral_code'),
        ('mutual_sip', '0008_alter_sip_no_of_investors_alter_sip_total_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sip',
            name='users',
        ),
        migrations.AddField(
            model_name='sip',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sips_taken', to='account.usersipdetails'),
        ),
    ]
