# Generated by Django 4.2.7 on 2024-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0008_remove_sip_description_remove_sip_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sip',
            name='min_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
