# Generated by Django 4.2.7 on 2024-03-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0009_sip_description_sip_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip_details',
            name='min_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sip_details',
            name='sip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_details', to='mutual_sip.sip'),
        ),
        migrations.CreateModel(
            name='SIP_DETAILSs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_investors', models.IntegerField(blank=True, default=0, null=True)),
                ('total_investment', models.FloatField(blank=True, default=0.0, null=True)),
                ('time_period', models.IntegerField()),
                ('current_value', models.FloatField(blank=True, default=0.0)),
                ('gain_value', models.FloatField(blank=True, default=0.0)),
                ('sip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip', to='mutual_sip.sip')),
            ],
        ),
    ]
