# Generated by Django 4.2.7 on 2024-03-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0010_alter_sip_details_min_amount_alter_sip_details_sip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sip_detailss',
            name='sip',
        ),
        migrations.DeleteModel(
            name='SIP_DETAILS',
        ),
        migrations.DeleteModel(
            name='SIP_DETAILSs',
        ),
    ]
