# Generated by Django 4.2.7 on 2023-12-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0010_remove_sip_users_sip_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='sip_photo',
            field=models.ImageField(max_length=300, null=True, upload_to='user_image'),
        ),
    ]
