# Generated by Django 4.2.7 on 2024-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0011_remove_sip_detailss_sip_delete_sip_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='current_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sip',
            name='gain_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sip',
            name='no_of_investors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sip',
            name='time_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sip',
            name='total_investment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
