# Generated by Django 4.2.7 on 2023-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0011_sip_sip_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sip',
            name='users',
        ),
        migrations.AddField(
            model_name='sip',
            name='users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
