# Generated by Django 4.2.7 on 2024-03-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0012_sip_current_value_sip_gain_value_sip_no_of_investors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sip',
            name='gain_value',
        ),
        migrations.RemoveField(
            model_name='sip',
            name='no_of_investors',
        ),
        migrations.RemoveField(
            model_name='sip',
            name='total_investment',
        ),
    ]
