# Generated by Django 4.2.7 on 2023-12-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0014_alter_sip_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='annual_return_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
