# Generated by Django 4.2.7 on 2023-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_userpurchaseorderdetails_installment_date_and_more'),
        ('mutual_sip', '0015_sip_annual_return_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='investment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sip',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='sips_taken', to='account.userpurchaseorderdetails'),
        ),
    ]
