# Generated by Django 4.2.7 on 2023-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_userbasicdetail_verification'),
        ('mutual_sip', '0016_alter_sip_investment_type_alter_sip_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='sips_taken', to='account.userpurchaseorderdetails'),
        ),
    ]
