# Generated by Django 4.2.7 on 2024-03-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, max_length=300, null=True, upload_to='user_image')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_no', models.CharField(max_length=12)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('verification', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdharCardVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card_front', models.ImageField(max_length=5000, upload_to='user_image')),
                ('adhar_card_back', models.ImageField(max_length=5000, upload_to='user_image')),
                ('adhar_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PanVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.ImageField(max_length=5000, upload_to='user_image')),
                ('pan_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserBasicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=40)),
                ('fullName', models.CharField(max_length=50)),
                ('d_o_b', models.DateField()),
                ('address_details', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('verification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchaseOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.FloatField(default=0.0)),
                ('member_status', models.CharField(default='active', max_length=100)),
                ('portfolio_no', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('investment_type', models.CharField(default='active', max_length=100)),
                ('sip_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sip_price', models.CharField(blank=True, max_length=500, null=True)),
                ('invested_period', models.CharField(blank=True, max_length=100, null=True)),
                ('installment_date', models.IntegerField(blank=True, null=True)),
                ('no_of_installment', models.IntegerField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True)),
            ],
        ),
    ]
