# Generated by Django 4.2.7 on 2024-03-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0010_alter_sip_details_min_amount_alter_sip_details_sip_and_more'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchaseorderdetails',
            name='sips',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_sip_details', to='mutual_sip.sip'),
        ),
    ]
