# Generated by Django 4.2.7 on 2023-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userbasicdetail_panverification_adharcardverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
