# Generated by Django 4.2.7 on 2024-03-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userpurchaseorderdetails_sips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousCurrentValueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('user_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userpurchaseorderdetails')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
