# Generated by Django 4.2.7 on 2024-03-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_previouscurrentvaluelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicdetail',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
