# Generated by Django 4.2.7 on 2023-12-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
