# Generated by Django 4.2.7 on 2024-03-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userbasicdetail_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchaseorderdetails',
            name='payment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
