# Generated by Django 4.2.7 on 2024-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userpurchaseorderdetails_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
