# Generated by Django 4.2.7 on 2024-03-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adharcardverify',
            name='adhar_card_back',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adharcardverify',
            name='adhar_card_front',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panverification',
            name='pan_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
