# Generated by Django 4.2.7 on 2023-12-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_usersipdetails_sip_list_usersipdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersipdetails',
            name='sip_list',
        ),
    ]
