# Generated by Django 4.2.7 on 2023-12-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0002_alter_sip_min_amount'),
        ('account', '0010_remove_usersipdetails_sip_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersipdetails',
            name='sips',
            field=models.ManyToManyField(related_name='users_sip_details', to='mutual_sip.sip'),
        ),
    ]
