# Generated by Django 4.2.7 on 2023-12-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0003_rename_no_of_investers_sip_no_of_investors_and_more'),
        ('account', '0011_usersipdetails_sips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersipdetails',
            name='sips',
        ),
        migrations.AddField(
            model_name='usersipdetails',
            name='sips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_sip_details', to='mutual_sip.sip'),
        ),
    ]
