# Generated by Django 4.2.7 on 2023-12-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0004_remove_sip_users_sip_users'),
        ('account', '0012_remove_usersipdetails_sips_usersipdetails_sips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersipdetails',
            name='sips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sip_details', to='mutual_sip.sip'),
        ),
    ]
