# Generated by Django 4.2.7 on 2023-12-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0004_remove_sip_users_sip_users'),
        ('account', '0013_alter_usersipdetails_sips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersipdetails',
            name='sips',
        ),
        migrations.AddField(
            model_name='usersipdetails',
            name='sips',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_sip_details', to='mutual_sip.sip'),
        ),
    ]
