# Generated by Django 4.2.7 on 2023-12-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_sip', '0007_alter_sip_users'),
        ('account', '0014_remove_usersipdetails_sips_usersipdetails_sips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersipdetails',
            name='sips',
        ),
        migrations.AddField(
            model_name='usersipdetails',
            name='sips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sip_details', to='mutual_sip.sip'),
        ),
    ]
