# Generated by Django 4.2.7 on 2023-12-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_usersipdetails_sips_usersipdetails_sips'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersipdetails',
            name='portfolio_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
