# Generated by Django 4.2.7 on 2023-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_usersipdetails_portfolio_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersipdetails',
            name='sips',
        ),
        migrations.AddField(
            model_name='usersipdetails',
            name='sips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
