# Generated by Django 4.2.7 on 2023-12-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_usersipdetails_gain_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchaseorderdetails',
            name='portfolio_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
