# Generated by Django 4.2.7 on 2023-12-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_delete_usersipdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchaseorderdetails',
            old_name='current_amount',
            new_name='sip_price',
        ),
    ]
