# Generated by Django 4.2.7 on 2023-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_rename_current_amount_userpurchaseorderdetails_sip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchaseorderdetails',
            name='installment_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpurchaseorderdetails',
            name='invested_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpurchaseorderdetails',
            name='no_of_installment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpurchaseorderdetails',
            name='sip_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
