# Generated by Django 4.2.7 on 2023-12-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_userbasicdetail_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
