# Generated by Django 4.2.7 on 2023-12-25 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbasicdetail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpurchaseorderdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpurchaseorderdetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
