# Generated by Django 4.2.7 on 2023-12-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_userbasicdetail_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchaseorderdetails',
            name='total_investment',
            field=models.IntegerField(blank=True, default=0.0),
        ),
    ]
