# Generated by Django 4.2.7 on 2023-12-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_userpurchaseorderdetails_total_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchaseorderdetails',
            name='total_investment',
        ),
        migrations.AlterField(
            model_name='userpurchaseorderdetails',
            name='investment_type',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
