# Generated by Django 4.2.7 on 2024-01-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_remove_userpurchaseorderdetails_total_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adharcardverify',
            name='adhar_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='panverification',
            name='pan_no',
            field=models.CharField(max_length=12),
        ),
    ]
