# Generated by Django 4.2.7 on 2024-01-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_adharcardverify_adhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adharcardverify',
            name='adhar_card_back',
            field=models.ImageField(max_length=5000, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='adharcardverify',
            name='adhar_card_front',
            field=models.ImageField(max_length=5000, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='panverification',
            name='pan_card',
            field=models.ImageField(max_length=5000, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='panverification',
            name='pan_no',
            field=models.CharField(max_length=10),
        ),
    ]
